FROM sstrigler/squeeze:latest
MAINTAINER Martin Diederich <martin.diederich@gmail.com>

# set env vars
ENV container docker
ENV LC_ALL C
ENV DEBIAN_FRONTEND noninteractive

# configure apt sources
RUN echo "deb http://archive.debian.org/debian-archive/debian-security/ squeeze/updates main contrib non-free \n\
deb http://archive.debian.org/debian/ squeeze main contrib non-free \n\
deb http://archive.debian.org/debian-backports squeeze-backports main" > /etc/apt/sources.list


# configure apt behaviour
RUN echo "Acquire::Check-Valid-Until "0"; \n\
APT::Get::Install-Recommends "false"; \n\
APT::Get::Install-Suggests "false"; \n\
APT::Get::Assume-Yes "true"; \n\
APT::Get::force-yes "true";" > /etc/apt/apt.conf.d/00-general


RUN apt-get update
RUN apt-get install -y apt-utils
RUN apt-key adv --keyserver keys.gnupg.net --recv 247F7E7E8066CC9A
RUN apt-get install debconf -y


ENV DEBIAN_FRONTEND noninteractive ENV HOME /root RUN apt-get update
RUN apt-get install -y acl vim wget curl git subversion acl htop nano procps psmisc sudo
RUN apt-get install -y zip
# install ssh RUN apt-get install -y openssh-server
# config ssh for easy access RUN sed -i 's/^PermitRootLogin/# PermitRootlogin/' /etc/ssh/sshd_config
RUN echo 'root:root' | chpasswd
RUN mkdir -p /root/.ssh


#Install Dependencies RUN apt-get upgrade -y
#RUN apt-get install -y build-essential autoconf
#RUN apt-get install -y wget curl openssl socat mysql-client python
#RUN apt-get install -y zlib1g zlib1g-dev libssl-dev libcurl4-openssl-dev libexpat1-dev gettext
#RUN apt-get -y install libmysqlclient-dev
#RUN apt-get -y install libxslt1-dev
#RUN apt-get -y install libpq-dev
#RUN apt-get install -y php-pear
#RUN apt-get install -y php5-dev
#RUN pear upgrade pear
#RUN pear channel-discover pear.phpunit.de
#RUN pear config-set auto_discover 1


RUN adduser --system --home /opt/authentic2 --shell /bin/bash --group --disabled-login authentic2
RUN apt-get install -y locales python-virtualenv python-pip
RUN dpkg-reconfigure locales
RUN apt-get install -y -t squeeze-backports python-django

#RUN apt-get install -y python-django-south python-django-auth-ldap python-lasso python-openid python-ldap python-m2crypto
RUN apt-get install -y python-lasso python-openid python-ldap python-m2crypto
RUN sudo -u authentic2 -i



# install typical requirements for testing
RUN apt-get install -y procps ssl-cert ca-certificates apt-transport-https python sudo curl net-tools netcat6

#cleanup
RUN apt-get clean



EXPOSE 3000

CMD ["/bin/bash"]